# Generated by Django 4.0.5 on 2022-07-01 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vardas')),
                ('surname', models.CharField(max_length=100, verbose_name='Pavarde')),
                ('duties', models.CharField(max_length=20, verbose_name='Pareigos')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektroninis pastas')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('description', models.CharField(help_text='trumpas aprasymas, apie 50 simboliu', max_length=50, verbose_name='Aprasymas')),
                ('category', models.CharField(blank=True, choices=[('a', 'CodeMonkey'), ('b', 'Hub'), ('c', 'Short'), ('d', 'TeamBuilding')], default='a', help_text='kategorija', max_length=1)),
                ('type', models.CharField(choices=[('a', 'Live'), ('b', 'InPerson')], max_length=1)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_planner.person', verbose_name='Atsakingas asmuo')),
            ],
        ),
    ]
