# Generated by Django 4.0.5 on 2022-07-18 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duties', models.CharField(blank=True, choices=[('a', 'Developer'), ('b', 'Support'), ('c', 'Testing'), ('d', 'Management')], max_length=50, verbose_name='Duties')),
                ('images', models.ImageField(default='default.jpg', upload_to='profile', verbose_name='Images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('description', models.CharField(help_text='Description about 50 simbols', max_length=50, verbose_name='Description')),
                ('category', models.CharField(blank=True, choices=[('a', 'CodeMonkey'), ('b', 'Hub'), ('c', 'Short'), ('d', 'TeamBuilding')], default='a', help_text='Category', max_length=1, verbose_name='Category')),
                ('type', models.CharField(choices=[('a', 'Live'), ('b', 'InPerson')], max_length=1, verbose_name='Type')),
                ('start_time', models.DateTimeField(verbose_name='Meeting start time')),
                ('end_time', models.DateTimeField(verbose_name='Meeting end time')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Meeting create time')),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_planner.person', verbose_name='Responsible person')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
            },
        ),
    ]
