# Generated by Django 4.0.5 on 2022-07-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='surname',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(blank=True, choices=[('a', 'CodeMonkey'), ('b', 'Hub'), ('c', 'Short'), ('d', 'TeamBuilding')], default='a', help_text='Category', max_length=1, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Meeting create time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(help_text='Description about 50 simbols', max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(verbose_name='Meeting end time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(verbose_name='Meeting start time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('a', 'Live'), ('b', 'InPerson')], max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='duties',
            field=models.CharField(blank=True, choices=[('a', 'Developer'), ('b', 'Support'), ('c', 'Testing'), ('d', 'Management')], max_length=50, verbose_name='Duties'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='images',
            field=models.ImageField(default='default.jpg', upload_to='profile', verbose_name='Images'),
        ),
    ]
