# Generated by Django 4.0.5 on 2022-07-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='duties',
            field=models.CharField(choices=[('a', 'Developer'), ('b', 'Support'), ('c', 'Testing'), ('d', 'Management')], max_length=50, verbose_name='Pareigos'),
        ),
    ]
