# Generated by Django 4.0.5 on 2022-07-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_planner', '0002_remove_person_name_remove_person_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='duties',
            field=models.CharField(blank=True, choices=[('a', 'Developer'), ('b', 'Support'), ('c', 'Testing'), ('d', 'Management')], max_length=50, verbose_name='Duties'),
        ),
    ]
