# Generated by Django 4.0.5 on 2022-07-10 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_planner', '0002_alter_person_duties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(blank=True, choices=[('a', 'CodeMonkey'), ('b', 'Hub'), ('c', 'Short'), ('d', 'TeamBuilding')], default='a', help_text='Category', max_length=1),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(help_text='Description about 50 simbols', max_length=50, verbose_name='Aprasymas'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_planner.person', verbose_name='Responsible person'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='duties',
            field=models.CharField(choices=[('a', 'Developer'), ('b', 'Support'), ('c', 'Testing'), ('d', 'Management')], max_length=50, verbose_name='Duties'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Surname'),
        ),
    ]
