# Generated by Django 4.0.5 on 2022-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_planner', '0003_alter_person_duties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(blank=True, choices=[(0, 'CodeMonkey'), (10, 'Hub'), (11, 'Short'), (20, 'TeamBuilding')], default='a', help_text='Category', max_length=1),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Meeting create time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(help_text='Description about 50 simbols', max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(verbose_name='Meeting end time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(verbose_name='Meeting start time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[(0, 'Live'), (1, 'InPerson')], max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='duties',
            field=models.CharField(blank=True, choices=[(0, 'Developer'), (10, 'Support'), (11, 'Testing'), (20, 'Management')], max_length=50, verbose_name='Duties'),
        ),
        migrations.AlterField(
            model_name='person',
            name='images',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Images'),
        ),
    ]
